### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by marianolongoort** [carorajcic/proyecto-pnt1#1]
Carrito
General
- [ ] Logo 
- [ ] Información institucional
- [ ] Contenido anónimo
- [ ] Navegar por productos y sus descripciones
- [ ] Mostrar productos por categoría
- [ ] Productos deshabilitados, deben visualizarse como pausados
- [ ] Productos sin stock, deben visualizarse igualmente
- [ ] Ver Sucursales con los datos de locación y contacto
- [ ] Restricciones por Sesiones y Roles
- [ ] Persistencia en SQL LocalDB
- [ ] Inicialización de DB

Cliente
- [ ] Auto registración con Rol y carrito activo
- [ ] Inicio Sesión 
- [ ] Actualizar datos contacto, Dirección y teléfono
- [ ] No modificar Email, DNI, Nombre, Apellido, etc.
- [ ] Agregar productos a carrito con inicio de sesión forzado
- [ ] Sin repetir proceso de agregar luego del inicio de sesión
- [ ] Revisión de carrito
- [ ] Modificar cantidades de manera independiente por ítem en el carrito - Sin validar stock
- [ ] Subtotales (Computado) y total en carrito (Computados)
- [ ] Limpiar carrito
- [ ] Realizar Comprar
- [ ] Total compra (Persistido)
- [ ] Carrito se desactiva al realizar la compra
- [ ] Carrito nuevo se instancia y se asigna al cliente
- [ ] Selección de sucursal
- [ ] Validar stock de sucursal antes de finalizar compra
- [ ] Oferta de sucursales que tengan stock
- [ ] Aviso de que no hay stock en ninguna sucursal
- [ ] Descontar de stock de sucursal
- [ ] Al finalizar compra visualizar
- [ ] Mensaje de agradecimiento
- [ ] Código de compra
- [ ] Sucursal seleccionada y datos de sucursal
- [ ] Historial de compras, listado
- [ ] Historial de compras (Id, Fecha, Sucursal, Monto) + Detalle con los ítems adquiridos
- [ ] Solo puede tener un carrito activo

Empleado
- [ ] Crear otro empleado con su rol correspondiente
- [ ] ABM Empleados
- [ ] Password automática por sistema
- [ ] Listar compras realizadas en el mes
- [ ] Orden desc Valor Compra
- [ ] Crear Productos, Categorías, Sucursales
- [ ] No se puede eliminar carritos
- [ ] No se puede eliminar productos
- [ ] No se puede eliminar categorías
- [ ] No se pueden eliminar compras
- [ ] No se puede eliminar directamente un stockItem
- [ ] Habilitar y/o deshabilitar Productos
- [ ] Agregar productos al stock de cada sucursal, cada sucursal, tiene su propio stock
- [ ] Se puede eliminar sucursal, solo si no tiene productos en stock (ningún o  todos los StockItems en 0)
- [ ] Solo se eliminaran si cantidad = 0 y es eliminado automáticamente por eliminar una sucursal

Restricciones / Generalidades
- [ ] Compra.Fecha
- [ ] No se puede duplicar Sucursal.Nombre
- [ ] No se puede duplicar Categoria.Nombre
- [ ] No se puede duplicar Cliente.DNI
- [ ] No se puede duplicar Empleado.NroEmpleado
- [ ] Un carrito inactivo, no puede modificarse bajo ningún concepto
- [ ] No se pueden eliminar los carritos de los clientes
- [ ] El valor unitario del carritoItem, debe actualizarse, al realizar cualquier modificación, según el precio que tenga vigente el producto "No desde el modelo, sino desde el controlador correspondiente"
